package-lock.json
package.json

Update webpack-dev-server package from to version 3.1.14 (for security reasons).

Update webpack-dev-server package

---

client/src/modules/shopping-list/index.jsx

[EOC-65] change toolbar content depending on user roles for lists

---

server/controllers/cohort.js
server/controllers/shoppingList.js
server/routes/cohort.js
server/routes/shoppingList.js

I did a bit of investigation before doing this task. I have found a nice article about error messages 
https://uxdworld.com/2018/05/30/how-to-write-good-error-messages/
Referring to the article all `err.message `sent from backend are replaced with custom messages, 
to make notifications understandable to the user. 
Previously using `err.message`,  we had something like this: 
which was not understandable to a non-technical user. 
Now all the messages are easy to understand.

[EOC-61] Fix server issues

---

client/src/modules/list/model/reducer.js

[EOC-81] go back from archived list to cohort

---

client/src/common/components/Toolbar/components/UserBar/UserBar.scss
client/src/modules/notification/Notification.scss
client/src/modules/notification/index.jsx

[EOC-90] Change notification position

---

client/src/app/styles/_buttons.scss
client/src/app/styles/index.scss
client/src/assets/images/icons/index.js
client/src/common/components/CardItem.jsx
client/src/common/components/CardItem.scss
client/src/common/components/CookieConsent.scss
client/src/common/components/Form.jsx
client/src/common/components/FormDialog.jsx
client/src/common/components/GridList.jsx
client/src/common/components/GridList.scss
client/src/common/utils/cookie.js
client/src/modules/archived/index.jsx
client/src/modules/authorization/AuthBox.jsx
client/src/modules/authorization/model/actions.js
client/src/modules/cohort/index.jsx
client/src/modules/dashboard/index.jsx
client/src/modules/list/components/InputBar/InputBar.jsx
client/src/modules/list/components/InputBar/InputBar.scss
client/src/modules/list/components/ItemsContainer.jsx
client/src/modules/list/index.jsx
client/src/modules/list/model/selectors.js
package.json

This branch includes changes from the eoc_97 branch which is not merged yet.
Files to review: Authbox.js, package.json, common/utils/cookie.js

[EOC-82] Add cookie constent on app

---

client/src/app/styles/_buttons.scss
client/src/common/components/ArchivedMessage.jsx
client/src/modules/cohort/Cohort.scss
client/src/modules/cohort/index.jsx
client/src/modules/list/index.jsx
server/controllers/cohort.js
server/controllers/list.js

[EOC-116] Archive list by link under list

---

client/src/app/styles/_forms.scss
client/src/assets/images/icons/index.js
client/src/common/components/CardItem.jsx
client/src/common/components/CardItem.scss
client/src/common/components/Dialog.scss
client/src/common/components/Form.jsx
client/src/common/components/FormDialog.jsx
client/src/common/components/GridList.jsx
client/src/modules/cohort/index.jsx
client/src/modules/cohort/model/actions.js
client/src/modules/dashboard/index.jsx
client/src/modules/list/index.jsx
client/src/modules/list/model/actions.js
server/controllers/cohort.js
server/controllers/list.js
server/models/list.model.js

Lists on dashboard are private by default.
List in cohorts: 
-when private - only visible to owner, 
-when public- visible to all cohort members

[EOC-119] On list creation select private public add lock icon for private list

---

client/src/app/styles/index.scss
client/src/modules/cohort/Cohort.scss
client/src/modules/cohort/components/CohortHeader.jsx
client/src/modules/cohort/components/CohortHeader.scss
client/src/modules/cohort/index.jsx
server/controllers/cohort.js

Update of title and description is perfomed, when click event is captured away from the element  which is currently in the edition or when "Enter" key is pressed on the keyboard.
Update fields are hiding when the click event is captured outside element which is currently in the edition.

[EOC-91] inline edit name description for cohort

---

client/src/common/components/CardItem.jsx
client/src/common/components/CardItem.scss
client/src/common/components/GridList.jsx
server/common/utils/index.js
server/controllers/list.js

[EOC-107] Additional info on list tiles

---

client/src/common/components/CardItem.jsx
client/src/common/components/CardItem.scss
client/src/common/components/GridList.jsx
server/common/utils/index.js
server/controllers/cohort.js
server/controllers/list.js

[EOC-129] Additional info on cohort tiles

---

client/src/modules/archived/index.jsx
client/src/modules/dashboard/index.jsx

[EOC-126] Display archive lists below active lists on dashboard

---

client/src/app/styles/index.scss
client/src/common/components/DescriptionTextarea.jsx
client/src/common/components/DescriptionTextarea.scss
client/src/common/components/NameInput.jsx
client/src/common/components/NameInput.scss
client/src/common/components/SortBox.scss
client/src/common/utils/helpers.js
client/src/modules/cohort/components/CohortHeader.jsx
client/src/modules/cohort/components/CohortHeader.scss
client/src/modules/list/List.scss
client/src/modules/list/components/ListHeader.jsx
client/src/modules/list/components/ListHeader.scss
client/src/modules/list/index.jsx
server/controllers/list.js

In this pull request I have also fixed a bug in cohort header ---> adding description or name with spaces only.

[EOC-125] inline edit title description for list

---

client/src/common/components/Members/components/MemberDetails.jsx
client/src/modules/cohort/index.jsx
client/src/modules/list/index.jsx

[EOC-144] Move archive cohort from toolbar to link

---

client/src/app/styles/_colors.scss
client/src/common/components/MessageBox.jsx
client/src/common/components/MessageBox.scss

[EOC-147] Check notification in SandTime - make ours more visible

---

client/src/common/components/Members/MembersBox.scss
client/src/common/components/Members/components/MemberButton.jsx
client/src/common/components/Members/components/MemberDetails.jsx
client/src/common/components/Members/components/MemberDetails.scss
client/src/common/components/Members/index.jsx

On mobile, box is displayed below users list.
On the desktop, it is as it was previously.

[EOC-143] - Change responsive behaviour on mobile

---

client/src/modules/list/components/ListItem.jsx
server/common/utils/helpers.js
server/controllers/list.js

Items toggling was broken. (no toggling on toggle buton, no DB update)
Now it works fine

Fix controller bug

---

client/src/common/components/Forms/TextInput.jsx
client/src/common/components/Forms/Textarea.jsx
client/src/common/components/Members/components/MemberDetails.jsx
client/src/common/components/Members/index.jsx
client/src/common/utils/helpers.js
client/src/modules/cohort/index.jsx
client/src/modules/cohort/model/selectors.js
client/src/modules/list/components/Items/InputBar/InputBar.jsx
client/src/modules/list/components/Items/ItemsList.jsx
client/src/modules/list/components/Items/ListItem/ListItem.jsx
client/src/modules/list/components/Items/ListItem/ListItem.scss
client/src/modules/list/components/Items/VotingBox/VotingBox.jsx
client/src/modules/list/components/Items/VotingBox/VotingBox.scss
client/src/modules/list/components/ItemsContainer.jsx
client/src/modules/list/components/ListHeader.jsx
client/src/modules/list/index.jsx
server/controllers/cohort.js
server/controllers/list.js

Viewer on the list: 
Member on the list:
Owner on the list:

[EOC-163, EOC-160,  EOC-164, EOC-165] Implementation of viewer role in front end for list

---

client/src/modules/list/components/ItemsContainer.jsx

Sorting didn't work for votes.

Add super hot fix

---

client/src/modules/list/components/Items/model/actions.js
server/controllers/list.js
server/routes/list.js

[EOC-148 ] Merge updateListItem with updateItemDetails controller.

---

server/controllers/comment.js

Viewers couldn't fetch the item's comments.

HOT FIX to eoc-153 Adding comments

---

client/src/common/components/Members/components/MemberDetails.jsx

[EOC-179] Do not show roles switches if disabled

---

client/src/assets/images/user.svg
client/src/common/components/Comments/Comment.jsx
client/src/common/components/Comments/Comment.scss
client/src/common/components/Members/components/MemberButton.jsx
client/src/common/components/Members/components/MemberButton.scss
client/src/common/components/Members/components/MemberDetails.jsx
client/src/common/components/Members/components/MemberDetails.scss
client/src/common/components/Toolbar/components/UserBar/UserBar.jsx
server/controllers/list.js

[EOC-175] Bug handle missing avatar

---

client/src/assets/images/user.svg
client/src/common/components/Members/components/MemberButton.jsx
client/src/common/components/Members/components/MemberButton.scss
client/src/common/components/Members/components/MemberDetails.jsx
client/src/common/components/Members/components/MemberDetails.scss
client/src/common/components/Members/index.jsx
client/src/common/components/Toolbar/components/UserBar/UserBar.jsx
server/controllers/list.js

The limit is set to 10.
When there are less than 10 users, dots are not displayed.
When there are more than 10 users, dots are displayed. 
After pressing dots all users are shown.

[EOC-176] Hide dots when not needed

---

package-lock.json
package.json
webpack.config.js
webpack.config.production.js

This is a dev build:
This is a production build:

[EOC-191] Add css autoprefixer configuration

---

client/src/common/components/PendingButton.jsx
client/src/modules/list/components/Items/ListItem/ListItem.jsx
client/src/modules/list/components/Items/ListItem/ListItem.scss
client/src/modules/list/components/Items/ListItem/constants.js
client/src/modules/list/components/Items/model/actions.js

The toggle button is currently disabled and the cursor is not-allowed as long as the toggle actions, resolves

[EOC -200]  bug prevent multiple click on item toggling

---

client/src/common/components/CardPlus.scss
client/src/common/components/CollectionView.scss
client/src/common/components/ListViewItem.jsx
client/src/common/components/ListViewItem.scss

[EOC-203] Reduce list view items height

---

server/seed/demoSeed/generateCohorts.js
server/seed/demoSeed/generateLists.js

This branch includes all changes from eoc_181 branch.
Files to review:
server/seed/demoSeed/generateCohorts.js
server/seed/demoSeed/generateLists.js

[EOC-185] Demo mode add more description

---

client/src/app/styles/_mixins.scss
client/src/common/components/DescriptionTextarea.jsx
client/src/common/components/DescriptionTextarea.scss
client/src/common/components/NameInput.jsx
client/src/common/components/NameInput.scss
client/src/modules/cohort/components/CohortHeader.jsx
client/src/modules/list/components/ListHeader.jsx
client/src/modules/list/components/ListHeader.scss

[EOC-196] editing list name and description on mobile additional save button

---

client/src/modules/list/components/Items/ItemsList.jsx
client/src/modules/list/components/ItemsContainer.scss

EOC-210] BUG User can not roll up the lists

---

client/src/modules/list/components/Items/ItemsList.jsx
client/src/modules/list/components/Items/ListArchivedItem/ListArchivedItem.jsx
client/src/modules/list/components/Items/ListArchivedItem/ListArchivedItem.scss
client/src/modules/list/components/Items/ListItem/ListItem.jsx
client/src/modules/list/components/Items/ListItem/ListItem.scss
client/src/modules/list/index.jsx

Web Sockets were not working because of a bad merge inside 
client/src/modules/list/index.jsx   file.
I have found "React can't call setState after a component is unmounted..." and fix is inside ListItem.jsx file.

Hotifx sockets

---

server/controllers/userAuth.js

Almost all functionality has been done in EOC-231 task. I added updating displayName and password in signup controller for already registered users in the situation that the user tries signup with the same email but uses other name or password

[EOC-234] Resend activation link if already registered

---

client/src/modules/list/components/Items/ItemsList.jsx
client/src/modules/list/components/Items/ListItem/ListItem.scss
package-lock.json
package.json

[EOC-244] Highlight new item when adding/cloning etc

---

client/src/app/index.jsx
client/src/common/components/Comments/CommentsList.jsx
client/src/common/components/Comments/NewComment.jsx
client/src/common/components/Forms/Textarea.jsx
client/src/common/context/socket-context.js
client/src/common/hoc/withSocket.jsx
client/src/modules/list/components/Items/InputBar/InputBar.jsx
client/src/modules/list/components/Items/ItemsList.jsx
client/src/modules/list/components/Items/ListArchivedItem/ListArchivedItem.jsx
client/src/modules/list/components/Items/ListItem/ListItem.jsx
client/src/modules/list/components/Items/ListItem/ListItem.scss
client/src/modules/list/components/Items/ListItemDescription/ListItemDescription.jsx
client/src/modules/list/components/Items/ListItemName/ListItemName.jsx
client/src/modules/list/components/Items/model/actions.js
client/src/modules/list/index.jsx
server/common/variables.js
server/sockets/index.js
server/sockets/list.js

Please review only the last two commits, as the previous belongs to EOC-250 PR.
Can't compare to EOC-250, because Github sees 52 files change.

[EOC-251] Adding comments to the item

---

client/src/app/index.jsx
client/src/common/context/socket-context.js
client/src/common/hoc/withSocket.jsx
client/src/modules/list/components/Items/InputBar/InputBar.jsx
client/src/modules/list/components/Items/ItemsList.jsx
client/src/modules/list/components/Items/ListArchivedItem/ListArchivedItem.jsx
client/src/modules/list/components/Items/ListItem/ListItem.jsx
client/src/modules/list/components/Items/ListItemDescription/ListItemDescription.jsx
client/src/modules/list/components/Items/ListItemName/ListItemName.jsx
client/src/modules/list/components/Items/model/actions.js
client/src/modules/list/index.jsx
server/common/variables.js
server/sockets/index.js
server/sockets/list.js

This branch includes changes from EOC - 250.
Please review, only 2 last commits.

[EOC-253] Cloning item

---

client/src/common/components/Members/components/MemberDetails.jsx
client/src/modules/list/index.jsx
client/src/modules/list/model/actions.js
server/controllers/list.js

[EOC-291] Guest can't leave the cohort shared list

---

client/src/modules/cohort/components/CohortHeader.jsx

You can see the .mov file of this BUG in Jira under EOC-418 task.

[EOC-418] During editing, the displayed value changes and the previous status/value appears

---

client/src/common/components/Activities/components/Activity.jsx
client/src/common/components/Activities/components/Activity.scss

[EOC-397] Activities - to long item name causes horizontal scroll within activities box

---

server/controllers/list.js

This task is related to EOC-420 which is already merged.
This task returned from QA.

[EOC-433] Add backend validation for name for creating list

---

client/src/common/components/Activities/model/actions.js
client/src/common/components/Members/model/actions.js
client/src/common/constants/variables.js
client/src/common/exceptions/ForbiddenException.js
client/src/common/exceptions/index.js
client/src/common/utils/fetchMethods.js
client/src/locales/en.json
client/src/modules/cohort/model/actions.js
client/src/modules/list/model/actions.js
client/src/modules/notification/Notification.scss
client/src/modules/notification/components/Notification.jsx
client/src/modules/notification/components/NotificationWithTimer.jsx
client/src/modules/notification/index.jsx
client/src/modules/notification/model/actions.js
client/src/modules/notification/model/reducer.js
client/src/modules/user/model/actions.js
server/controllers/userAuth.js

To show notification regarding no authorization or end of user's session I had to restore error capturing in action's catch statement and pass this error to the notification, and there, by checking its type display a notification with timer feature or not.
I had a problem with a time value to the notification message. Regardless of the way I was passing it, there were no spaces between the time value and the rest of the notification's message. I have no idea why this was happening. I found some workaround and it's working but I don't know if this should be written in that way: File NotificationWithTimer.jsx, line 41-49.

[EOC-406] Terminate other user sessions after password changes

---

README.md

Kuba added a description to the repository. 
EOC license updated.

[EOC-462] Github fill out description and update readme

---

client/src/common/components/Dropdown.jsx

Bug fixed for all touch devices.
I have also added some to code to close the menu on view change - what was expected behavior from a long time ago.

[EOC-289] Cannot close the profile menu

---

client/src/common/components/MessageBox.scss
client/src/modules/notification/Notification.scss

[EOC-442] Notification Missing spaces between text and email address

---

client/src/modules/list/components/Items/ListArchivedItem/ListArchivedItem.scss

[EOC-272] [BUG] Long name for the item is out of the box

---

client/src/modules/list/components/Items/ListItem/ListItem.jsx
client/src/modules/list/components/Items/ListItem/ListItem.scss
client/src/modules/list/components/Items/ListItemName/ListItemName.scss

[EOC-471] Display item all along the item

---

client/src/modules/list/model/actions.js
client/src/modules/list/model/reducer.js
server/common/utils/helpers.js
server/controllers/list.js
server/sockets/cohort.js
server/sockets/helpers/index.js

After discussion, we discover that we don't have to create new methods `responseWith...`
but we can use the existing one, but we have to make extra checks inside these methods and it will work both inside controllers and sockets.

[EOC-473] Socket create helper for response with methods

---

client/src/modules/list/components/Items/ListArchivedItem/ListArchivedItem.jsx
client/src/modules/list/components/Items/model/actions.js
client/src/modules/list/components/Items/model/reducer.js
server/controllers/list.js

Summary: Archiving item works correctly, we can perform restoring also, but restoring item doesn't send and display `editedBy` value. Now it is fixed.

[EOC-454] Cannot restore and archive item

---

client/src/modules/notification/components/Notification.jsx

Some action (login, demo) display notification without passing additional data to the message and in notification there was no check if data exist or not.

[EOC-489] After sign in to application white page is displayed

---

server/controllers/list.js

Remove list owner controller wasn't associated with sockets and didn't emit socket events

EOC-482 [BUG]Update members on list view when owner is removed

---

client/src/app/components/Layout/Layout.jsx

I fix this issue according to [Scroll Restoration](https://reacttraining.com/react-router/web/guides/scroll-restoration) from [React Training](https://reacttraining.com).

[EOC-428] Sub-pages are not opening on the top part of the site

---

server/controllers/cohort.js
server/controllers/comment.js
server/controllers/list.js
server/index.js
server/sockets/index.js

The task is mainly related to require orders in index.js server file. As @Ciunkos said, reffering to the https://github.com/sandstreamdev/eoc/pull/289#discussion_r317961574 , import orderd should be not dependent on socketInstance initialization. 
Now it's refactored and it "works as nature always wanted 🐐 🌿 🌿".

[EOC 443] Improvement refactor socket initialization and passing socket instance

---

client/src/locales/en.json

[EOC-494] Change add item placeholder to item name placeholder

---

client/src/common/components/HomeLink.jsx
client/src/common/components/HomeLink.scss
client/src/modules/user/AuthBox/components/LinkExpired.jsx
client/src/modules/user/AuthBox/components/PasswordRecoveryForm.jsx
client/src/modules/user/AuthBox/components/ResetPassword.jsx
client/src/modules/user/AuthBox/components/SuccessMessage.jsx

[EOC-503] Add link to home page on forms

---

client/src/modules/user/UserProfile/ResourcePanel.jsx

Mariusz found an issue in task ECO-521.

[EOC-521][FIX] Prevent displaying resource if undefined in ResourcePanel component

---

server/common/utils/userUtils.js

[EOC-521] [HOT-FIX] Remove user account issue with deleted resources

---

client/src/common/components/Members/index.jsx
client/src/common/components/Members/model/actions.js
client/src/common/utils/helpers.js
client/src/modules/cohort/index.jsx
client/src/modules/list/index.jsx
server/common/variables.js
server/mailer/common/styles.js
server/mailer/index.js
server/mailer/invite/template.js

Update invitation email template and content

---

client/src/common/components/TilesViewItem.jsx

[EOC-555] Remove fav icon on tile view

---

server/controllers/userAuth.js
server/mailer/common/styles.js
server/mailer/confirmation/template.js
server/mailer/index.js
server/mailer/invite/template.js
server/mailer/reports/weekly-content.js
server/mailer/reports/weekly-template.js
server/mailer/reset-password/template.js

Update confirmation link and reset password email template and content

---

client/src/common/components/Members/components/InviteNewUser.scss
client/src/common/components/Members/components/MembersForm.jsx
client/src/common/components/Members/components/MembersForm.scss
client/src/common/components/Members/index.jsx
client/src/locales/en.json

This is part ONE of this task. The second part will be added in a separated pull request.
It includes: 
- clear button, 
- click outside
- email validation

[EOC-546] add animations to add member form - PART ONE

---

client/src/common/utils/events.js
client/src/modules/cohort/components/CohortDescription.jsx
client/src/modules/cohort/components/CohortName.jsx
client/src/modules/list/components/Items/ListItemDescription/ListItemDescription.jsx
client/src/modules/list/components/Items/ListItemName/ListItemName.jsx
client/src/modules/list/components/ListHeader.jsx

[EOC-417] Proposal add notification additional info when leaving saved data

---

client/src/common/components/Dialog.jsx
client/src/locales/en.json
client/src/modules/user/UserProfile/DeleteAccount.jsx
client/src/modules/user/UserProfile/DeleteDialog.jsx
client/src/modules/user/UserProfile/DeleteForm.jsx
client/src/modules/user/model/actions.js
server/controllers/userAuth.js
server/routes/authorization.js

[EOC-561] Remove account that was created with google login (add common dialogs and flows)

---

Jenkinsfile
server/config/auth.js
server/mailer/index.js

I added `GOOGLE_CALLBACK_URL` to the env file and passed it to the `GoogleStrategy` setup. I tried to build this URL dynamically:
```
`${HOST}/auth/google/callback`
```
but then I always received sth like this: `http://localhost/http://localhost/auth/google/callback`

[EOC-551] Fix callbackURL issue

---

client/src/app/styles/_buttons.scss
client/src/app/styles/_forms.scss
client/src/common/components/Activities/Activities.scss
client/src/common/components/DescriptionTextarea.scss
client/src/common/components/NameInput.scss
client/src/modules/list/components/Items/InputBar/InputBar.scss
client/src/modules/user/AuthBox/components/PasswordChangeForm.scss
client/src/modules/user/AuthBox/components/SignInForm.scss
client/src/modules/user/AuthBox/components/SignUpForm.scss

[EOC-587] Fix all submit buttons styles on Safari 

---

client/src/common/components/DescriptionTextarea.scss
client/src/common/components/NameInput.scss
client/src/modules/list/components/Items/InputBar/InputBar.scss

[EOC-959] Fix small styles issue (Safari)

---

client/src/locales/en.json

[EOC-598] Delete account - add instruction about the possibility to delete lists/cohorts instead of changing roles

---

client/src/modules/user/UserProfile/EmailReports.jsx
client/src/modules/user/UserProfile/EmailReports.scss

[EOC-602] Move send report button above report frequency options

---

client/src/app/components/Layout/Layout.jsx
client/src/app/components/Layout/Toolbar/Toolbar.jsx
client/src/app/components/Layout/Toolbar/Toolbar.scss
client/src/common/components/CookieConsentBox.jsx
client/src/modules/privacy-policy/index.jsx
client/src/modules/user/AuthBox/AuthBox.jsx
landing/css/style.css
landing/index.html
server/config/auth.js
server/controllers/userAuth.js
server/routes/authorization.js

[EOC-606][EOC-607] Add button (link) to demo on landing (next to try now)/On Demo Mode add header ‘demo’ on topBar

---

client/src/modules/list/components/Items/ListItemName/ListItemName.jsx

I've added the same validation as we have while adding a new item.

[EOC-583] Add input validation when editing item name

---

landing/index.html

[EOC-613] Landing texts: Start your own journey, We had designed an intuitive (…) that makes (…)

---

package-lock.json
package.json

I have tested on Safari, Firefox, and Chrome and it looks the same. 😀
Mariusz can also do some cross-browser testing ⚔️⚔️

[EOC-622] Add normalize.css and test if it not crashes app layout

---

landing/css/style.css

[EOC-606] Fix button styles on landing

---

server/sockets/helpers/index.js

[EOC-621] Lock handler causes displaying errors in the console

---

client/src/app/styles/_buttons.scss
client/src/modules/user/AuthBox/components/SignInForm.jsx
client/src/modules/user/AuthBox/components/SignUpForm.jsx
client/src/modules/user/model/actions.js

I fixed the issue reported by Mariusz. Additionally, I fixed a few small issues related with disabling sign in/sign up buttons.
Change that fixe the main issue is in `client/src/modules/user/model/actions.js` file.

[HOT_FIX] Fix sign in via login and password, fix small pending issue
