sandstreamdev/eoc

- .eslintrc
- client/src/common/components/CreationForm.jsx
- client/src/common/components/Form.jsx
- client/src/modules/shopping-list/components/InputBar/InputBar.jsx
I have tried with `autoFocus` prop on input field and it works perfectly, but because this was so easy it made me curious if this the proper way to do it in React. 
Referring to react documentation and linked post from StackOverflow, the proper implementation is to use refs on inputs. 
Because react re-renders intelligently some parts of component independently `autoFocus` prop may not always work as expected.
[https://stackoverflow.com/questions/28889826/set-focus-on-input-after-render](url)
[https://reactjs.org/docs/refs-and-the-dom.html](url)
> [EOC-86] Add autofocus functionality for forms

- client/src/modules/dashboard/index.jsx
Dialog boxes did not close due to a `return` to the switch statement. Changed to `break`
> [HOTFIX]- Add hotfix for closing dialogs

- client/src/modules/cohort/index.jsx
- client/src/modules/cohort/model/actions.js
- client/src/modules/cohort/model/selectors.js
- client/src/modules/list/index.jsx
- client/src/modules/list/model/actions.js
- server/controllers/cohort.js
- server/controllers/list.js
- server/models/cohort.model.js
- server/models/list.model.js
I was not sure what I should do with item schema. We have there authorId and purchaserId fields. Should we leave them as they are or change purchaserId to ownerId and auhorId to memberId?
In my opinion in 'items' case the most proper solution would be to leave purchaserId and change authorId to ordererId. These would be names reflecting the true meaning of these fields. Because of small difference between authorId and OrdererId I decided to leave item schema as it is: with authorId and PurchaserId. In all other cases I removed purchaserIds, changed ordererIds to memberIds and adminIds to ownerIds.
> [EOC-118] Admin + purchaser => owner and member

- client/src/app/components/Layout/Layout.jsx
- client/src/app/styles/_buttons.scss
- client/src/common/components/ArchivedMessage.jsx
- client/src/common/components/ArchivedMessage.scss
- client/src/common/components/CardItem.jsx
- client/src/common/components/CardItem.scss
- client/src/common/components/Dialog.jsx
- client/src/common/components/Dialog.scss
- client/src/common/components/FormDialog.jsx
- client/src/common/components/GridList.jsx
- client/src/common/components/GridList.scss
- client/src/common/components/Members/MembersBox.scss
- client/src/common/components/Members/components/MemberDetails.jsx
- client/src/common/components/Members/components/MemberDetails.scss
- client/src/common/components/Members/components/MembersForm.jsx
- client/src/common/components/Members/components/MembersForm.scss
- client/src/common/components/Members/index.jsx
- client/src/common/components/Preloader.jsx
- client/src/common/components/Preloader.scss
- client/src/modules/cohort/components/ArchivedCohort.jsx
- client/src/modules/cohort/components/CohortHeader.jsx
- client/src/modules/cohort/components/CohortHeader.scss
- client/src/modules/cohort/components/Cohorts.jsx
- client/src/modules/cohort/index.jsx
- client/src/modules/dashboard/index.jsx
- client/src/modules/list/List.scss
- client/src/modules/list/components/ArchivedList.jsx
- client/src/modules/list/components/ListHeader.jsx
- client/src/modules/list/components/ListHeader.scss
- client/src/modules/list/index.jsx
As we agreed, preloader animations were added everywhere they were needed, except of actions/features concerning list's items, because their code is changed and edited in Adam's tasks.
> [EOC-111] Add preloader animation where needed

- client/src/app/styles/_colors.scss
- client/src/common/components/Comments/Comment.jsx
- client/src/common/components/Comments/Comment.scss
- package.json
I used react-linkify lib to detect link in text and convert them to a a tags.
> [EOC-170] Add links functionality to comments

- package-lock.json
- package.json
- server/app.js
Because of this: "Warning The default server-side session storage, MemoryStore, is purposely not designed for a production environment. It will leak memory under most conditions, does not scale past a single process, and is meant for debugging and developing." from `express-session`
> Fix production sessions storage

- README.md
- server/seed/demoSeed/generateUsers.js
I used [avatars](https://avatars.dicebear.com/) API.
To remove all demo users with old API run:
```
npm run clear-demo
```
To remove main demo user with old API:
```
mongo --shell
use eoc
db.users.deleteOne({ _id: ObjectId("<DEMO_USER_ID from server/common/variables.js>" ) })
```
> [EOC-180] Change avatar service in demo

- client/src/app/styles/_forms.scss
**Mayer Reset.css** or **normalize.css**
do not apply any styles for :disabled, :active pseudo classes.
We need to handle this manually and test across browsers. 
I have tried with normalize.css but whole app styles were broken and need a lot of fixing and reviewing what is broken ( which will take a few hours to fix).
For now, I have added my own fix, but we need to merge and test it on production server. I can't reproduce this bug on my browser.
> [EOC-199] Reset css [BUG]

- server/sockets/index.js
After consultation with Kuba, I decided to catch error but do anything with the error, because sockets are not the main functionality in our app so the user doesn't have to know what is going on under the hood (that app is using WebSockets connection).
I have also added forceNew, to force reconnection when error or disconnection occurs.
> [EOC-280] Add socket.io error handling 

- client/src/modules/list/components/Items/model/actions.js
- client/src/modules/list/model/actions.js
- server/common/utils/helpers.js
- server/common/utils/helpers.test.js
- server/controllers/list.js
- server/models/item.model.js
- server/routes/list.js
Item is now flagged as isDeleted and not removed from the database.
`deleteItem() ` controller is now unnecessary because deleting item is managed via updateItem controller.
> [EOC-309] Item - do not delete, flag as deleted

- server/common/variables.js
- server/sockets/index.js
This error causes those issues with Sockets that disconnects randomly on Chrome. 
https://github.com/socketio/socket.io/issues/3259#issuecomment-448058937
Referring to a comment linked above, socket.io library changed default ping timeout from 60000ms in (v2.0.4) to 5000ms in (v2.1.0+), which is not enough for some browsers and they get disconnected randomly. 
Overwriting this parameter fixed the issue, at least on localhost 😄
> [EOC-BUG] Add longer pingTimeout to prevent from disconnection

- client/src/app/styles/_variables.scss
- client/src/modules/about/About.scss
The background was broken for resolutions greater than QWHD. Now it's fixed for QWHD and even for 4K. 
**Before:**
**After:**
> [EOC-423] Fix background on about us page 

- client/src/app/components/Layout/Layout.jsx
Lines from 145 to 159 look identical to lines from 102 to 116, so I've tried to not repeat them by creating a method,
```
renderRoutes() => (
<Fragment>
Repeated routes here...
</Fragment>
)
```
and call it in those two places. Unfortunately, **<Framgment>** can't be used within `<Switch>` component and app crashed. 
So finally I left it as it is.
> [EOC-377] Add routes for reseting password, confirmation account for logged user

- client/src/common/components/Members/components/MemberDetails.jsx
- client/src/common/components/Members/components/MemberDetails.scss
- client/src/common/components/Members/components/MemberDetailsHeader.scss
I have noticed that this bug appears only on the lists where I wasn't the owner.
Now it's fixed and looks the same on every view and device. Tested on Chrome, Mozilla and Safari.
> [EOC-367] Fix member details box size

- client/src/app/components/Layout/Layout.jsx
- client/src/app/model/middleware.js
- client/src/app/model/store.js
- client/src/common/model/actions.js
- client/src/modules/cohort/model/reducer.js
- client/src/modules/list/model/reducer.js
- server/controllers/cohort.js
- server/sockets/cohort.js
- server/sockets/helpers/index.js
- server/sockets/index.js
1. On entering the app, on socket connection, the user joins all metadata rooms for resources he has access to.
2. To test if joining works I refactor updateCohort to emit data for new cohort meta-data room. 
3. To prevent dispatching an action twice for a user who performed this action I create redux middleware which prevents dispatching an action if the user's id is the same as the performer's id.
4. To clear unnecessary data that the user gets on views like 'about' or 'privacy policy' I check for changing the route in layout component and clear lists or cohorts data if that change occurs. I tried to not saving unnecessary data but logic was complicated. I had to compare the current route (we have no access to react-router outside of component) with event type to decide if that data has …
> [EOC-464] Joining and leaving rooms for all available resources on entering or exiting the app.

- client/src/modules/user/AuthBox/components/LinkExpired.scss
- client/src/modules/user/AuthBox/components/PasswordRecoveryForm.jsx
- client/src/modules/user/AuthBox/components/PasswordRecoveryForm.scss
- client/src/modules/user/AuthBox/components/ResetPassword.scss
- client/src/modules/user/AuthBox/components/SuccessMessage.scss
I could not reproduce this error. I checked locally on the dev server, on mobile and always user name and email was displayed. But I found display error:
To fix this I changed styles of the password-recovery-form component: removed fixed-width to make it more responsive and added ellipsis if the user's email address is very long and change font-size on smaller screens.
To maintain greater uniformity I change the width styles in all the components in this series: `LinkExpired`, `PasswordRecoveryForm`, `ResetPassword` and `SucessMessage`.
> [EOC-488] Set new password form is not displaying user name

- client/src/modules/list/index.jsx
- client/src/modules/list/model/actions.js
The problem occurred when the guest tried to archive the cohort's list. They were redirected to the cohort view but they had no access to it so they got the '404' page. Now guests are redirected to dashboard.
> [EOC-455][BUG] Code 404 when user archived sacks.

- client/src/modules/list/model/reducer.js
- server/sockets/list.js
Item wasn't removed via socket because of sending invalid data name: `sourceListId` instead of `listId` and frontend didn't recognize it.
> [EOC-486] Moving item between lists ( move to option) fix

- client/src/common/components/FormDialog.jsx
I couldn't save a cohort or sack when I entered whitespaces in the name field. We validate name field and we don't allow to save name with whitespaces only.
But there was an analogical situation with the description field. The user could save cohort with the description with whitespaces only.
Because the description field is optional I don't display any warnings but replace string with whitespaces only with an empty string.
> [EOC-429] Cannot edit the name after the creates "Sacks" and "Cohorts" when user enter whitespace in name field

- client/src/modules/cohort/components/CohortDescription.scss
- client/src/modules/list/components/ListHeader.scss
A `.mov` file showing how this issue is fixed tou can find in Jira EOC-539 task, under attachments sections.
https://jira2.sanddev.com/browse/EOC-539
> [EOC-539]  When the description for the sack or cohort is too long, all text is invisible

- client/src/app/model/store.js
To make this working we would have to set `'process.env.NODE_ENV': JSON.stringify('production')` webpack plugin but since v. 4 defining mode='production' makes it for us: [webpack docs](https://webpack.js.org/guides/production/#specify-the-environment).
Unfortunately, I couldn't test it locally because I was unable to run the production environment :-(
> [EOC-578] Disable access to redux via redux-developer-tools on production

- client/src/common/components/Activities/Activities.scss
> Topbar icons alignment hotfix

- client/src/common/components/Comments/CommentsList.jsx
- client/src/common/components/Comments/NewComment.jsx
- client/src/common/components/Forms/Textarea.jsx
- client/src/common/components/Forms/Textarea.scss
I needed to unify the comment field to use default placeholder cause safari treats ::before ::after elements placing differently and it was an issue with missing top border on iOS safari.
> [EOC-586] Fix safari bug related with new comment Textarea

- client/src/app/styles/_buttons.scss
We need to remember to always explicitly add border-radius: 0 when styling, cause Safari default behavior is to add some 3px border-radius 😵😵😵
**Before:**
**After:**
> Fix description button styles on safari

- server/index.js
Because of :
I changed the MongoClient config according to [mongoose doc](https://mongoosejs.com/docs/deprecations.html)
> [EOC-626] MongoClient 'deprecated warning' in console
